### ISSUE TITLE
Hover: Location and format of nullability info

### ISSUE THREAD

**Issue by maenu** [maenu/method-nullability-plugin#2]
Move to return documentation.
On new line.
Numbers bold, background light blue.
If no return documentation, add return paragraph, unless void.
If no data, hint at no data in same format.

**Comment by lukaszbinden** [comment]
Not clear how/where to display nullability info when javadoc is not of proper format. Devising a possible solution.

**Comment by lukaszbinden** [comment]
Ok, as suggested, adding a "fake" return paragraph

**Comment by lukaszbinden** [comment]
what about methods with primitive return value?
e.g. java.util.Map.size()
Returns:
the number of key-value mappings in this map
0% check the returned value (0 out of 85365 invocations)

**Comment by maenu** [comment]
Primitive types are not nullable, but have a default value. Hence, they don't need to be annotated with nullability.
